Consider the below code to answer further questions:

import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Ans. Yes, there is a difference in the data type of variables list_ and array_list. The list_ variable is a Python list, while the array_list variable is a NumPy array.

Here's the code to print the data types of both variables:

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print('Data type of list_:', type(list_))
print('Data type of array_list:', type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.


In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Data type of each element in list_
for i in range(len(list_)):
    print('Data type of element', i+1, 'in list_:', type(list_[i]))

# Data type of each element in array_list
for i in range(len(array_list)):
    print('Data type of element', i+1, 'in array_list:', type(array_list[i]))


Data type of element 1 in list_: <class 'str'>
Data type of element 2 in list_: <class 'str'>
Data type of element 3 in list_: <class 'str'>
Data type of element 4 in list_: <class 'str'>
Data type of element 5 in list_: <class 'str'>
Data type of element 1 in array_list: <class 'numpy.str_'>
Data type of element 2 in array_list: <class 'numpy.str_'>
Data type of element 3 in array_list: <class 'numpy.str_'>
Data type of element 4 in array_list: <class 'numpy.str_'>
Data type of element 5 in array_list: <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list


In [5]:
array_list = np.array(object = list_, dtype = int)

Yes, there will be a difference in the data type of the elements present in list_ and array_list. When we create the array_list with the dtype parameter set to int, all the elements in the list_ will be converted to integers.

Here's the code to print the data type of each element in list_ and array_list after the modification:

In [6]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Data type of each element in list_
for i in range(len(list_)):
    print('Data type of element', i+1, 'in list_:', type(list_[i]))

# Data type of each element in array_list
for i in range(len(array_list)):
    print('Data type of element', i+1, 'in array_list:', type(array_list[i]))


Data type of element 1 in list_: <class 'str'>
Data type of element 2 in list_: <class 'str'>
Data type of element 3 in list_: <class 'str'>
Data type of element 4 in list_: <class 'str'>
Data type of element 5 in list_: <class 'str'>
Data type of element 1 in array_list: <class 'numpy.int32'>
Data type of element 2 in array_list: <class 'numpy.int32'>
Data type of element 3 in array_list: <class 'numpy.int32'>
Data type of element 4 in array_list: <class 'numpy.int32'>
Data type of element 5 in array_list: <class 'numpy.int32'>


Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size



In [9]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]

num_array = np.array(num_list)

# find the shape of num_array
print("Shape of num_array: ", num_array.shape)

# find the size of num_array
print("size of num_array: ",num_array.size)

Shape of num_array:  (2, 3)
size of num_array:  6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.


In [10]:
import numpy as np

# create a numpy array of zeros with shape (3, 3)
zeros_array = np.zeros((3, 3))

print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [11]:
import numpy as np

# create an identity matrix of shape (5, 5)
identity_matrix = np.eye(5)

print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
